language: node_js
node_js:
- 12
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: FLCJ2Jisqm3Ua42oHRCYBrU9hKdn/7vEcVC9cjCbvG9xzO/OqMyecxjLNu+D/S3SWAAtw4UVakDjoNlDXBJ7qQF0QB7uqJ1TEZO/OPP4pCYcfORXxFvOFD9oyGBnNGnKp3ZLHp6u/l30U8hlRxRJViCdAIHTAN6nuL40gV3KT8MWXaMPWiJ1tZ6/G7uh9DvyWWCChYycEXp5pCCOOTslLpuJFf8HLptslzWqcGHQry4lvJ3LKR45ka7Rs4L33zSdg2WFNgCwP9BXnXWL3cCHJr9R7ZgnCdiigvPG7NDUWYwFJqUtufF5aqBxQBwnO/O2/nKtlZ+G+JTiv2seHJYUNrNyuZCRu1iJzG81YdWrpGL8Fas4ts9Eux/y1/EyaAK0RE6C0zaFYgOU2WuGd617WnmZI9rljq0eg2ngk8if7dcLdWs31ezVJqUXW5w2G1K2PDFEv7TyrVTZxvhnmG/YM9ESWOrnBivKl4oKPI5DVS0L2KQv1G6JohwlPyXhtTMuaCaxAeVeGwPZqh69NvNh2FwZcswtKcW1sYOVTsDxMIo9LN7etRqRshNRn1YyILgd9mM0QszQVljLaRBhQa21bw2J8GIECQApGwi9GBluyxVegs7J/iVLe6KOL4roSZE4pQwK7bC/q/MMQraaPIU73uBjGtk1JLdkYrBCADhoS2Q=
  app: new-my-flat-app
